import { NextRequest, NextResponse } from "next/server";
import nodemailer from "nodemailer";
import { OAuth2Client } from "google-auth-library";
import { PlanItem, TicketData, UserPreferences, TravelOption } from "@/lib/store";

interface SendPlanPayload {
  credential: string;
  plan: PlanItem[];
  ticket?: TicketData | null;
  preferences?: UserPreferences | null;
  selectedTravel?: TravelOption | null;
}

function escapeHtml(input: string) {
  return input
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#39;");
}

function buildPlanHtml(payload: Omit<SendPlanPayload, "credential">, recipientEmail: string) {
  const { ticket, selectedTravel, preferences, plan } = payload;

  const planRows = plan
    .map(
      (item) => `
      <tr>
        <td style="padding:10px 12px;border-bottom:1px solid #2b3140;color:#f6f7f9;font-weight:600;vertical-align:top;">${escapeHtml(item.time)}</td>
        <td style="padding:10px 12px;border-bottom:1px solid #2b3140;color:#f6f7f9;vertical-align:top;">
          <div style="font-weight:700;margin-bottom:4px;">${escapeHtml(item.title)}</div>
          <div style="color:#c8cfda;margin-bottom:4px;">${escapeHtml(item.description)}</div>
          <div style="color:#9ca8bc;font-size:12px;">${escapeHtml(item.reasoning || "")}</div>
        </td>
      </tr>
    `
    )
    .join("");

  const preface = `
    <p style="margin:0 0 8px;color:#d5dbea;">Hi there,</p>
    <p style="margin:0 0 16px;color:#c8cfda;">Here is your MatchDay plan, sent to <strong>${escapeHtml(recipientEmail)}</strong>.</p>
  `;

  return `
  <div style="font-family:Inter,Segoe UI,Arial,sans-serif;background:#0f1117;padding:24px;color:#f6f7f9;">
    <div style="max-width:680px;margin:0 auto;border:1px solid #2b3140;border-radius:14px;overflow:hidden;background:#151925;">
      <div style="padding:18px 20px;background:linear-gradient(90deg,#4f7cff,#7c4dff);">
        <h2 style="margin:0;font-size:20px;color:#ffffff;">MatchDay Plan</h2>
        <p style="margin:6px 0 0;font-size:13px;color:#eaf0ff;">Your session summary is ready</p>
      </div>

      <div style="padding:18px 20px;">
        ${preface}

        <div style="margin:0 0 14px;padding:12px;border:1px solid #2b3140;border-radius:10px;background:#101420;">
          <div style="color:#d7deee;font-size:13px;line-height:1.6;">
            <div><strong>Match:</strong> ${escapeHtml(ticket?.match || "Not available")}</div>
            <div><strong>Venue:</strong> ${escapeHtml(ticket?.venue || "Not available")}</div>
            <div><strong>Kickoff:</strong> ${escapeHtml(ticket?.kickoffTime || "Not available")} ${escapeHtml(ticket?.date || "")}</div>
            <div><strong>Gate / Seat:</strong> ${escapeHtml(ticket?.gate || "-")} · ${escapeHtml(ticket?.stand || "-")} ${escapeHtml(ticket?.section || "")} ${escapeHtml(ticket?.seat || "")}</div>
            <div><strong>Travel:</strong> ${escapeHtml(selectedTravel?.label || preferences?.travelMode || "Not set")}</div>
          </div>
        </div>

        <table role="presentation" cellspacing="0" cellpadding="0" style="width:100%;border-collapse:collapse;border:1px solid #2b3140;border-radius:10px;overflow:hidden;">
          <thead>
            <tr style="background:#1b2130;">
              <th align="left" style="padding:10px 12px;color:#9fb0cc;font-size:12px;letter-spacing:0.04em;text-transform:uppercase;width:120px;">Time</th>
              <th align="left" style="padding:10px 12px;color:#9fb0cc;font-size:12px;letter-spacing:0.04em;text-transform:uppercase;">Plan</th>
            </tr>
          </thead>
          <tbody>
            ${planRows}
          </tbody>
        </table>

        <p style="margin:16px 0 0;color:#96a2ba;font-size:12px;">Generated by MatchDay AI Concierge.</p>
      </div>
    </div>
  </div>
  `;
}

export async function POST(req: NextRequest) {
  try {
    const { credential, plan, ticket, preferences, selectedTravel } =
      (await req.json()) as SendPlanPayload;

    if (!credential || !Array.isArray(plan) || plan.length === 0) {
      return NextResponse.json(
        { error: "credential and non-empty plan are required" },
        { status: 400 }
      );
    }

    const googleClientId = process.env.GOOGLE_CLIENT_ID || process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
    if (!googleClientId) {
      return NextResponse.json(
        { error: "GOOGLE_CLIENT_ID is not configured" },
        { status: 500 }
      );
    }

    const smtpHost = process.env.SMTP_HOST;
    const smtpPort = Number(process.env.SMTP_PORT || 587);
    const smtpUser = process.env.SMTP_USER;
    const smtpPass = process.env.SMTP_PASS;
    const fromEmail = process.env.SMTP_FROM || smtpUser;

    if (!smtpHost || !smtpUser || !smtpPass || !fromEmail) {
      return NextResponse.json(
        { error: "SMTP environment variables are incomplete" },
        { status: 500 }
      );
    }

    const oauthClient = new OAuth2Client(googleClientId);
    const ticketResult = await oauthClient.verifyIdToken({
      idToken: credential,
      audience: googleClientId,
    });

    const payload = ticketResult.getPayload();
    const recipient = payload?.email;

    if (!recipient || !payload?.email_verified) {
      return NextResponse.json(
        { error: "Google account email is unavailable or unverified" },
        { status: 401 }
      );
    }

    const transporter = nodemailer.createTransport({
      host: smtpHost,
      port: smtpPort,
      secure: smtpPort === 465,
      auth: {
        user: smtpUser,
        pass: smtpPass,
      },
    });

    const html = buildPlanHtml(
      { plan, ticket, preferences, selectedTravel },
      recipient
    );

    await transporter.sendMail({
      from: fromEmail,
      to: recipient,
      subject: `Your MatchDay plan — ${ticket?.match || "Session Summary"}`,
      html,
    });

    return NextResponse.json({ ok: true, email: recipient });
  } catch (error) {
    console.error("[send-plan-email] Error:", error);
    return NextResponse.json(
      { error: "Failed to send email. Please try again." },
      { status: 500 }
    );
  }
}
